var communicationrequest__tests_8py =
[
    [ "fhirclient.models.communicationrequest_tests.CommunicationRequestTests", "classfhirclient_1_1models_1_1communicationrequest__tests_1_1_communication_request_tests.html", "classfhirclient_1_1models_1_1communicationrequest__tests_1_1_communication_request_tests" ]
];