var medicinalproductindication_8py =
[
    [ "fhirclient.models.medicinalproductindication.MedicinalProductIndication", "classfhirclient_1_1models_1_1medicinalproductindication_1_1_medicinal_product_indication.html", "classfhirclient_1_1models_1_1medicinalproductindication_1_1_medicinal_product_indication" ],
    [ "fhirclient.models.medicinalproductindication.MedicinalProductIndicationOtherTherapy", "classfhirclient_1_1models_1_1medicinalproductindication_1_1_medicinal_product_indication_other_therapy.html", "classfhirclient_1_1models_1_1medicinalproductindication_1_1_medicinal_product_indication_other_therapy" ]
];