var namespacefhirclient_1_1models_1_1organizationaffiliation__tests =
[
    [ "OrganizationAffiliationTests", "classfhirclient_1_1models_1_1organizationaffiliation__tests_1_1_organization_affiliation_tests.html", "classfhirclient_1_1models_1_1organizationaffiliation__tests_1_1_organization_affiliation_tests" ]
];