var namespacefhirclient_1_1models_1_1immunizationrecommendation =
[
    [ "ImmunizationRecommendation", "classfhirclient_1_1models_1_1immunizationrecommendation_1_1_immunization_recommendation.html", "classfhirclient_1_1models_1_1immunizationrecommendation_1_1_immunization_recommendation" ],
    [ "ImmunizationRecommendationRecommendation", "classfhirclient_1_1models_1_1immunizationrecommendation_1_1_immunization_recommendation_recommendation.html", "classfhirclient_1_1models_1_1immunizationrecommendation_1_1_immunization_recommendation_recommendation" ],
    [ "ImmunizationRecommendationRecommendationDateCriterion", "classfhirclient_1_1models_1_1immunizationrecommendation_1_1_immunization_recommendation_recommendation_date_criterion.html", "classfhirclient_1_1models_1_1immunizationrecommendation_1_1_immunization_recommendation_recommendation_date_criterion" ]
];