var namespacefhirclient_1_1models_1_1medicinalproductundesirableeffect__tests =
[
    [ "MedicinalProductUndesirableEffectTests", "classfhirclient_1_1models_1_1medicinalproductundesirableeffect__tests_1_1_medicinal_product_undesirable_effect_tests.html", "classfhirclient_1_1models_1_1medicinalproductundesirableeffect__tests_1_1_medicinal_product_undesirable_effect_tests" ]
];