var namespacefhirclient_1_1models_1_1medicinalproductindication =
[
    [ "MedicinalProductIndication", "classfhirclient_1_1models_1_1medicinalproductindication_1_1_medicinal_product_indication.html", "classfhirclient_1_1models_1_1medicinalproductindication_1_1_medicinal_product_indication" ],
    [ "MedicinalProductIndicationOtherTherapy", "classfhirclient_1_1models_1_1medicinalproductindication_1_1_medicinal_product_indication_other_therapy.html", "classfhirclient_1_1models_1_1medicinalproductindication_1_1_medicinal_product_indication_other_therapy" ]
];