var namespacefhirclient_1_1models_1_1medicinalproductcontraindication =
[
    [ "MedicinalProductContraindication", "classfhirclient_1_1models_1_1medicinalproductcontraindication_1_1_medicinal_product_contraindication.html", "classfhirclient_1_1models_1_1medicinalproductcontraindication_1_1_medicinal_product_contraindication" ],
    [ "MedicinalProductContraindicationOtherTherapy", "classfhirclient_1_1models_1_1medicinalproductcontraindication_1_1_medicinal_product_contraindication_other_therapy.html", "classfhirclient_1_1models_1_1medicinalproductcontraindication_1_1_medicinal_product_contraindication_other_therapy" ]
];