var namespacefhirclient_1_1models_1_1immunizationrecommendation__tests =
[
    [ "ImmunizationRecommendationTests", "classfhirclient_1_1models_1_1immunizationrecommendation__tests_1_1_immunization_recommendation_tests.html", "classfhirclient_1_1models_1_1immunizationrecommendation__tests_1_1_immunization_recommendation_tests" ]
];