var namespacefhirclient_1_1models_1_1researchdefinition__tests =
[
    [ "ResearchDefinitionTests", "classfhirclient_1_1models_1_1researchdefinition__tests_1_1_research_definition_tests.html", "classfhirclient_1_1models_1_1researchdefinition__tests_1_1_research_definition_tests" ]
];