var observationdefinition__tests_8py =
[
    [ "fhirclient.models.observationdefinition_tests.ObservationDefinitionTests", "classfhirclient_1_1models_1_1observationdefinition__tests_1_1_observation_definition_tests.html", "classfhirclient_1_1models_1_1observationdefinition__tests_1_1_observation_definition_tests" ]
];