var visionprescription_8py =
[
    [ "fhirclient.models.visionprescription.VisionPrescription", "classfhirclient_1_1models_1_1visionprescription_1_1_vision_prescription.html", "classfhirclient_1_1models_1_1visionprescription_1_1_vision_prescription" ],
    [ "fhirclient.models.visionprescription.VisionPrescriptionLensSpecification", "classfhirclient_1_1models_1_1visionprescription_1_1_vision_prescription_lens_specification.html", "classfhirclient_1_1models_1_1visionprescription_1_1_vision_prescription_lens_specification" ],
    [ "fhirclient.models.visionprescription.VisionPrescriptionLensSpecificationPrism", "classfhirclient_1_1models_1_1visionprescription_1_1_vision_prescription_lens_specification_prism.html", "classfhirclient_1_1models_1_1visionprescription_1_1_vision_prescription_lens_specification_prism" ]
];